create a user profile
lys1k/io_todo_app pull request #4
Opened 2022-04-08 14:47 UTC by lys1k

2022-04-08 15:43 UTC, Deutscher862 commented
There are some conflicts you need to resolve first

2022-04-08 16:11 UTC, Deutscher862 requested changes

2022-04-08 16:11 UTC, Deutscher862 commented on backend/src/main/java/application/model/user/User.java
> +    private String password;
I assume we won't keep unencrypted password in the database. Or is it only temporary?

2022-04-08 16:11 UTC, Deutscher862 commented on backend/src/main/java/application/payload/response/JwtResponse.java
> +}
Git requires an empty line at the end of each file:
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-04-12 08:30 UTC, lys1k commented on backend/src/main/java/application/controller/TestController.java
> +}
True.

2022-04-12 08:40 UTC, lys1k commented on backend/src/main/java/application/model/user/User.java
> +    private String password;
Yes, that's my mistake.

2022-04-13 20:19 UTC, merged